name: grpc-tools Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write #  to fetch code (actions/checkout)

jobs:
  linux_build:
    name: Linux grpc-tools Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          depth: 2
      
      - name: diffctx
        uses: williamfzc/diffctx@v0.3.10
        with:
          lang: node
